create table if not exists product_raw
(
    id                 bigint generated by default as identity
        primary key,
    source             varchar(30)  not null,
    external_id        varchar(150) not null,
    content_hash       varchar(64)  not null,
    raw_json           text         not null,
    last_seen_at       timestamp    not null,
    normalized_at      timestamp,
    normalizer_version integer,
    created_at         timestamp    not null,
    updated_at         timestamp,
    constraint uk_product_raw_source_external_id
        unique (source, external_id)
);


create index if not exists idx_product_raw_source
    on product_raw (source);

create index if not exists idx_product_raw_normalized
    on product_raw (source, normalized_at);

create table if not exists product_source
(
    id   bigint generated by default as identity
        primary key,
    code varchar(255) not null,
    name varchar(255) not null,
    constraint uk_product_source_code
        unique (code)
);

create table if not exists provider
(
    id        bigint generated by default as identity
        primary key,
    source_id bigint       not null,
    code      varchar(255),
    name      varchar(255) not null,
    constraint fk_provider_product_source
        foreign key (source_id) references product_source (id),
    constraint uk_provider_source_code
        unique (source_id, code)
);

create table if not exists product
(
    id                   bigint generated by default as identity
        primary key,
    source_id            bigint       not null,
    provider_id          bigint       not null,
    type                 varchar(255) not null,
    product_code         varchar(255) not null,
    product_name         varchar(255) not null,
    content              text,
    base_rate            numeric(5, 2),
    max_rate             numeric(5, 2),
    min_monthly_limit    bigint,
    max_monthly_limit    bigint,
    min_age              integer,
    max_age              integer,
    earn_max_amt         bigint,
    earn_percent         integer,
    min_tenure_months    integer,
    requires_homeless    boolean      not null,
    requires_householder boolean      not null,
    apply_url            varchar(255),
    created_at           timestamp    not null,
    updated_at           timestamp,
    constraint fk_product_product_source
        foreign key (source_id) references product_source (id),
    constraint fk_product_provider
        foreign key (provider_id) references provider (id),
    constraint uk_product_source_product_code
        unique (source_id, product_code)
);

create table if not exists product_option
(
    id                bigint generated by default as identity
        primary key,
    product_id        bigint       not null,
    intr_rate_type    varchar(255) not null,
    intr_rate_type_nm varchar(255),
    save_trm          integer      not null,
    intr_rate         numeric(5, 2),
    intr_rate2        numeric(5, 2),
    constraint fk_product_option_product
        foreign key (product_id) references product (id)
);

create table if not exists product_keyword
(
    id           bigint generated by default as identity
        primary key,
    product_id   bigint       not null,
    keyword_code varchar(255) not null,
    constraint fk_product_keyword_product
        foreign key (product_id) references product (id),
    constraint uk_product_keyword_product_keyword_code
        unique (product_id, keyword_code)
);
